### PR TITLE
E-727 and Closed Loop Control commands

### PR DESCRIPTION
**Pull request by AugustoHorita**
I am working with the PIE727 module and couldn't find support for gains and notch configuration.
I implemented this code which works for us. I created a new class for PIE727 and also a header file with Closed Loop parameters and necessary structures. Included functions to set the CL parameters, and put the read function for these parameters in the poll thread.

There is a bug though, which I noticed also previously (also without this modification). If I use the asynRecord communication with the PI module, the poll thread starts to get timeouts for getting RAM parameters ("SPA?" commands) and position ("POS" commands) as soon as I set the ".OEOS" field in the asynRecord. I was thinking of maybe implementing a semaphore for this communication. (not yet done)

### CODE REVIEW

**Comment by kmpeters** [comment]
> There is a bug though, which I noticed also previously (also without this modification). If I use the asynRecord communication with the PI module, the poll thread starts to get timeouts for getting RAM parameters ("SPA?" commands) and position ("POS" commands) as soon as I set the ".OEOS" field in the asynRecord. I was thinking of maybe implementing a semaphore for this communication. (not yet done)

@AugustoHorita, are you able to send commands like ``SPA?`` to the controller without causing driver errors by leaving the ``OEOS`` blank and instead adding a ``\n`` to the end of command in the ``AOUT`` field?   Sending ``SPA?\n`` is much less intuitive, but if it works that could avoid having to change the driver further.

**Comment by AugustoHorita** [comment]
> > There is a bug though, which I noticed also previously (also without this modification). If I use the asynRecord communication with the PI module, the poll thread starts to get timeouts for getting RAM parameters ("SPA?" commands) and position ("POS" commands) as soon as I set the ".OEOS" field in the asynRecord. I was thinking of maybe implementing a semaphore for this communication. (not yet done)
> 
> @AugustoHorita, are you able to send commands like `SPA?` to the controller from the asyn record without causing driver errors by leaving the `OEOS` blank and instead adding a `\n` to the end of command in the `AOUT` field? Sending `SPA?\n` is much less intuitive, but if it works that could eliminate the need to change the driver further (and possibly introduce new bugs).

First of all, @kmpeters: thanks for your feedback and detailed explanation.
I will try to send the command like you suggested and get back here to inform.

**Comment by AugustoHorita** [comment]
@kmpeters...Sending the commands like you suggested worked fine! Thanks one more time for your help.

**Comment by kmpeters** [comment]
> Applying these features to most of the piezo controllers is outside the scope of this pull request. I'll create an issue for that.

https://github.com/epics-motor/motorPIGCS2/issues/11

**Pull request merged**
